---
title: "self-prioritization in same-fast effect 1a"
output: html_notebook
---

```{r}
# load packages
library(tidyverse)
library(ggplot2)
```

读取数据并合并
```{r}
df_raw <- list.files(file.path("../rawdata"), pattern = "exp1A_.*\\.csv$") %>%
  # 对读取到的所有.out文件x都执行函数read.table
  lapply(function(x) read.csv(file.path("../rawdata", x), header = TRUE)) %>%
    # 读取被试人口学信息
  lapply(function(df) mutate(df,subj_idx = as.numeric(jsonlite::fromJSON(response[5])$Q0), 
          gender = jsonlite::fromJSON(response[6]),#
          year = jsonlite::fromJSON(response[7])$Q0,
          education = jsonlite::fromJSON(response[8])$Q0,
          dist = view_dist_mm[9],
          rt = as.numeric(rt)))%>%
  bind_rows()
```

# 数据预处理
```{r}
df <- df_raw %>% 

  # 选择变量
  select(subj_idx, 
         #gender, 
         #year, 
         #education, 
         #dist, 
         rt, 
         correct_response, 
         correct, 
         key_press, 
         Image, 
         word, 
         condition,
         trial_type) %>% 
  # 选择试次
  dplyr::filter(trial_type == "psychophysics" & 
                condition != "prac" & 
                Image != "img/T_ambi40.png")%>% 
  # 添加列：matchness, selfness
  mutate(
    matchness =
      case_when(
        subj_idx %% 2 == 1 & correct_response == "j" ~ "match",
        subj_idx %% 2 == 1 & correct_response == "f" ~ "mismatch", 
        subj_idx %% 2 == 0 & correct_response == "f" ~ "match",
        subj_idx %% 2 == 0 & correct_response == "j" ~ "mismatch"),
    selfness = 
      case_when(
        word == '自我' ~ "selfness",
        .default = as.character("others")
      )) %>%
  # 剔除无关变量
  select(-correct_response, 
         -key_press, 
         -Image, 
         -word,
         -trial_type)
df
```
# 描述性统计
```{r}
df_desc <- df %>%
          select(everything())%>%
          group_by(condition,
                   matchness,
                   selfness,
                   #subj_idx
                   )%>%
          summarize(n = n(),
                    rt = mean(rt, na.rm = TRUE))%>%
          ungroup()
df_desc
```
# 方差分析
```{r}
model <- aov(rt ~ matchness * selfness, data = df)

# 查看方差分析结果
summary(model)
TukeyHSD(model, "matchness")
TukeyHSD(model, "selfness")
```

