---
title: "self-prioritization in same-fast effect 1a"
output: html_notebook
---

```{r}
# load packages
library(tidyverse)
library(ggplot2)
```

```{r}
getwd()

```


读取数据并合并
```{r}
df_raw <- list.files(file.path("./2_4_1_1_RawData"), pattern = "exp1A_.*\\.csv$") %>%
  # 对读取到的所有.out文件x都执行函数read.table
  lapply(function(x) read.csv(file.path("./2_4_1_1_RawData", x), header = TRUE)) %>%
    # 读取被试人口学信息
  lapply(function(df) mutate(df,subj_idx = as.numeric(jsonlite::fromJSON(response[5])$Q0), 
          gender = jsonlite::fromJSON(response[6]),
          year = jsonlite::fromJSON(response[7])$Q0,
          education = jsonlite::fromJSON(response[8])$Q0,
          dist = view_dist_mm[9],
          rt = as.numeric(rt)))%>%
  bind_rows()
```

# 数据预处理
```{r}
df <- df_raw %>% 

  # 选择变量
  select(subj_idx, 
         gender, 
         year, 
         #education, 
         #dist, 
         rt, 
         correct_response, 
         correct, 
         key_press, 
         Image, 
         word, 
         condition,
         trial_type) %>% 
  # 选择试次
  dplyr::filter(trial_type == "psychophysics" & 
                condition != "prac" & 
                Image != "img/T_ambi40.png")%>% 
  # 添加列：matchness, label, ACC
  mutate(
    matchness =
      case_when(
        subj_idx %% 2 == 1 & correct_response == "j" ~ "match",
        subj_idx %% 2 == 1 & correct_response == "f" ~ "mismatch", 
        subj_idx %% 2 == 0 & correct_response == "f" ~ "match",
        subj_idx %% 2 == 0 & correct_response == "j" ~ "mismatch"),
    ACC = 
      case_when(
        correct == "false" ~ 0, 
        correct == "true" ~ 1),
    label = 
      case_when(
        subj_idx %% 6 == 1 & Image == "img/C_ambi40.png" ~ "self",
        subj_idx %% 6 == 1 & Image == "img/H_ambi40.png" ~ "friend",
        subj_idx %% 6 == 1 & Image == "img/S_ambi40.png" ~ "stranger",
        subj_idx %% 6 == 2 & Image == "img/C_ambi40.png" ~ "friend",
        subj_idx %% 6 == 2 & Image == "img/H_ambi40.png" ~ "stranger",
        subj_idx %% 6 == 2 & Image == "img/S_ambi40.png" ~ "self",
        subj_idx %% 6 == 3 & Image == "img/C_ambi40.png" ~ "friend",
        subj_idx %% 6 == 3 & Image == "img/H_ambi40.png" ~ "self",
        subj_idx %% 6 == 3 & Image == "img/S_ambi40.png" ~ "stranger",
        subj_idx %% 6 == 4 & Image == "img/C_ambi40.png" ~ "stranger",
        subj_idx %% 6 == 4 & Image == "img/H_ambi40.png" ~ "friend",
        subj_idx %% 6 == 4 & Image == "img/S_ambi40.png" ~ "self",
        subj_idx %% 6 == 5 & Image == "img/C_ambi40.png" ~ "stranger",
        subj_idx %% 6 == 5 & Image == "img/H_ambi40.png" ~ "self",
        subj_idx %% 6 == 5 & Image == "img/S_ambi40.png" ~ "friend",
        subj_idx %% 6 == 0 & Image == "img/C_ambi40.png" ~ "self",
        subj_idx %% 6 == 0 & Image == "img/H_ambi40.png" ~ "stranger",
        subj_idx %% 6 == 0 & Image == "img/S_ambi40.png" ~ "friend",),
    )  %>%
  # 剔除无关变量
  select(-correct_response, 
         -correct,
         -key_press, 
         -Image, 
         -word,
         -trial_type,
         -condition)
df
```


```{r}
#正确率计算
df_acc <- df %>%
  dplyr::mutate(ACC = ifelse(ACC == 1,1,0)) %>%
  dplyr::group_by(subj_idx,
                  matchness,
                  label
                  )%>%
  dplyr::summarise(
    N = length(ACC),
    countN = sum(ACC),
    ACC = sum(ACC) / length(ACC)
  ) 
  df_acc
```


```{r}
df_acc <- df_acc %>%
    select(subj_idx,matchness,label,ACC) %>%
   pivot_wider(names_from = c("label", "matchness"), values_from = "ACC")
  
write.csv(df_acc,file = "exp1a_acc.csv")
```
# 描述性统计
```{r}
df_desc <- df %>%
          select(everything())%>%
          dplyr::filter(ACC == 1)%>%
          group_by(subj_idx,
                   matchness,
                   label)%>%
          summarize(n = n(),
                    rt = mean(rt, na.rm = TRUE))%>%
          ungroup()
df_desc
df_desc %>% 
  select(-n) %>% 
pivot_wider(names_from = c("label", "matchness"), values_from = "rt") %>% 
write_csv("exp1a_rt.csv")

```
# 方差分析
```{r}
model <- aov(rt ~ matchness * selfness, data = df)

# 查看方差分析结果
summary(model)
TukeyHSD(model, "matchness")
TukeyHSD(model, "selfness")
```

